/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.math.BigDecimal;
import java.io.IOException;
import java.util.Date;

import yahoofinance.YahooFinance;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;

import yahoofinance.Stock;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.XYChart;
import javafx.stage.Stage;


public class App extends Application {
    @Override public void start(Stage stage) {

        stage.setTitle("Dow Jones Line Chart");
        //defining the axes
        final NumberAxis xAxis = new NumberAxis();
        final NumberAxis yAxis = new NumberAxis();
        xAxis.setLabel("Time Taken");
        //creating the chart
        final LineChart<Number,Number> lineChart = 
                new LineChart<Number,Number>(xAxis,yAxis);
                
        lineChart.setTitle("Stock Monitoring");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        //initializing a queue that holds arraylists which will hold the stock's data
        Queue<ArrayList<Object>> dataHolder = new LinkedList<>();

        //while loop to keep getting the stock data over and over
        while (true) {

            //try catch block to get the stock data
            try {

                //initializing a list that will hold the stock's price and time it was retreived from the API
                ArrayList<Object> list1 = new ArrayList<>();

                //the dow jones data being saved into a Stock variable
                Stock stock = YahooFinance.get("Dow Jones Industrial Average");

                //the stock's price being retrieved
                BigDecimal stockPrice = stock.getQuote().getPrice();

                //date being recorded
                Date stockDate = new Date();

                //adding the time the stock's data was retrieved 
                list1.add(stockDate);
                //adding the stock's price at the moment in time in the list
                list1.add(stockPrice);

                //adding the list into the queue
                dataHolder.add(list1);

                Stage newStage = new Stage();

                start(newStage);

                //defining a series
                XYChart.Series series = new XYChart.Series();
                series.setName("My portfolio");

                //populating the series with data
                series.getData().add(new XYChart.Data(stockDate, stockPrice));
        
                Scene scene  = new Scene(lineChart,800,600);
                lineChart.getData().add(series);
       
                stage.setScene(scene);
                stage.show();

            //catch block to catch errors from the API fetching the data
            } catch (IOException error) {

                //printing that an error has happened
                System.out.println("error occured");

            }
        }
        

    }
}
